name: Android NDK Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Android NDK
      uses: android-actions/setup-android@v3
      with:
        ndk-version: '21.4.7075529'

    - name: Debug - List files
      run: |
        echo "当前目录结构:"
        find . -type f -name "*.mk" -o -name "*.cpp" -o -name "*.c" | head -20
        echo "Android.mk 内容:"
        if [ -f "Android.mk" ]; then
          cat Android.mk
        fi

    - name: Clean previous build
      run: |
        [ -d "obj" ] && rm -rf obj && echo "Cleaned obj directory"
        [ -d "libs" ] && rm -rf libs && echo "Cleaned libs directory"

    - name: Build with NDK
      run: |
        # 设置环境变量并构建
        export NDK_PROJECT_PATH=$(pwd)
        $ANDROID_NDK_ROOT/ndk-build -v  # 添加 -v 参数查看详细输出

    - name: Check build results
      run: |
        echo "构建结果:"
        find . -name "*.so" -o -name "*.a" | head -20
        if [ -d "libs" ]; then
          echo "libs 目录内容:"
          ls -la libs/
          find libs/ -type f
        fi

    - name: Rename library file
      run: |
        if [ -f "libs/arm64-v8a/lib5.so.fix.so" ]; then
          mv "libs/arm64-v8a/lib5.so.fix.so" "libs/arm64-v8a/lib5.so.fix"
          echo "File renamed successfully"
        else
          echo "lib5.so.fix.so not found, checking available files:"
          find libs/ -name "*.so" -o -name "*.fix" 2>/dev/null || echo "No libs directory"
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ndk-build-output
        path: |
          libs/
          obj/
