name: Build Android Shared Library

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download and setup Android NDK
      run: |
        # 下载 Android NDK
        wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip -q android-ndk-r25b-linux.zip
        echo "ANDROID_NDK_ROOT=$(pwd)/android-ndk-r25b" >> $GITHUB_ENV
        echo "NDK_PATH=$(pwd)/android-ndk-r25b" >> $GITHUB_ENV
        
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make g++
        
    - name: Configure and Build
      run: |
        mkdir -p build
        cd build
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$NDK_PATH/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=android-28 \
          -DCMAKE_MAKE_PROGRAM=make \
          -DCMAKE_BUILD_TYPE=Release
        make -j4
        
    - name: Check generated files
      run: |
        find build -name "*.so" | xargs -I {} file {} || echo "No .so files found"
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-lib-fix_gg
        path: build/lib*.so
        retention-days: 30
