name: Build Android Shared Library

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        abi: [arm64-v8a, armeabi-v7a, x86_64]
        android-platform: [android-28, android-29, android-30]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Android NDK
      uses: android-actions/setup-android@v3
      
    - name: Install CMake
      run: sudo apt-get install -y cmake
        
    - name: Configure and Build
      env:
        ANDROID_ABI: ${{ matrix.abi }}
        ANDROID_PLATFORM: ${{ matrix.android-platform }}
      run: |
        mkdir -p build_${{ matrix.abi }}_${{ matrix.android-platform }}
        cd build_${{ matrix.abi }}_${{ matrix.android-platform }}
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=$ANDROID_ABI \
          -DANDROID_PLATFORM=$ANDROID_PLATFORM \
          -DCMAKE_BUILD_TYPE=Release
        make -j4
        
    - name: Verify shared library
      run: |
        echo "=== Generated .so files ==="
        find . -name "*.so" -type f | while read file; do
          echo "File: $file"
          file "$file" || true
          echo "---"
        done
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-lib-${{ matrix.abi }}-${{ matrix.android-platform }}
        path: |
          build_*/lib*.so
        retention-days: 30
