name: Build Android Shared Library

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download and Setup Android NDK
      run: |
        # 下载指定版本的 Android NDK
        wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip -q android-ndk-r25b-linux.zip
        echo "NDK_PATH=$(pwd)/android-ndk-r25b" >> $GITHUB_ENV
        
    - name: Install Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake make
        
    - name: Configure with CMake
      run: |
        mkdir -p build
        cd build
        cmake .. \
          -DCMAKE_TOOLCHAIN_FILE=$NDK_PATH/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=arm64-v8a \
          -DANDROID_PLATFORM=android-28 \
          -DCMAKE_BUILD_TYPE=Release
          
    - name: Build the Library
      run: |
        cd build
        make -j4
        
    - name: Verify Generated Files
      run: |
        find build -name "*.so" -type f | xargs -I {} file {} || echo "No .so files found"
        
    - name: Upload Shared Library Artifact
      uses: actions/upload-artifact@v4
      with:
        name: libfix_gg-android
        path: build/lib*.so
        retention-days: 30
